---
abstract: 'Fetch a story from a fiction website'
author:
  - 'Kathryn Andersen <perlkat@katspace.org>'
build_requires:
  File::Find: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-FetchStory
requires:
  Date::Format: 0
  EBook::EPUB: 0
  Encode::ZapCP1252: 0
  File::Basename: 0
  File::Copy: 0
  File::Temp: 0
  Getopt::Long: 2.34
  HTML::Entities: 0
  HTML::Strip: 0
  HTML::Tidy::libXML: 0
  Module::Pluggable: 0
  Pod::Usage: 0
  YAML::Any: 0
version: 0.1201
